version: '3.8'

services:

  web1:
    image: httpd:latest
    volumes:
      - webdata:/usr/local/apache2/htdocs/
    networks:
      - internal

  web2:
    image: httpd:latest
    volumes:
      - webdata:/usr/local/apache2/htdocs/
    networks:
      - internal

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web1
      - web2
    networks:
      - internal

networks:
  internal:
    driver: bridge

volumes:
  webdata: